apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: cekit-builder
  namespace: devspaces-images
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: cekit-builder
  namespace: devspaces-images
spec:
  source:
    git:
      uri: https://github.com/cgruver/dev-workspace-utilities.git
      ref: main
    contextDir: "cekit-builder"
  strategy:
    dockerStrategy:
      dockerfilePath: "./cekit-builder.Containerfile"
  output:
    to:
      kind: ImageStreamTag
      name: cekit-builder:latest