name: dev-tools/dev-workspace-base
from: registry.access.redhat.com/ubi9/ubi-minimal
version: ubi9
packages:
  manager: microdnf
  manager_flags: "--disableplugin=subscription-manager --setopt=tsflags=nodocs --setopt=install_weak_deps=0"
artifacts:
- name: entrypoint
  path: entrypoint.sh
  target: entrypoint.sh
  dest: /
modules:
  repositories:
  - path: "../modules"
  install:
  - name: base
  - name: container-tools
run:
  entrypoint:
  - "/entrypoint.sh"